CREATE TABLE shop_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    shop_order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_public_id UUID NOT NULL,
    product_name_at_purchase VARCHAR(255) NOT NULL,
    price_at_purchase INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_shop_order FOREIGN KEY (shop_order_id) REFERENCES shop_orders (id)
);